const BookingData = [
  {
    id: 1,
    user: "Athul",
    startDate: "2025-03-01",
    endDate: "2025-03-05",
    address: "Kochi, Kerala",
    paymentStatus: "Paid",
    status: "Confirmed",
    amount: "₹5000",
    contractAmount: "₹5000",
    staffAccepted: true,
    userConfirmed: true,
    staffMessage: "Payment completed, booking confirmed!",
    staffId: "5",
    staffName: "Rajesh Kumar",
  },
  {
    id: 2,
    user: "Athul",
    startDate: "2025-04-10",
    endDate: "2025-04-12",
    address: "Dubai, UAE",
    paymentStatus: "Pending",
    status: "Pending",
    amount: "AED 800",
    contractAmount: "₹8000",
    staffAccepted: false,
    userConfirmed: false,
    staffMessage: "",
    staffId: "1",
    staffName: "John Doe",
  },
  {
    id: 3,
    user: "Rahul",
    startDate: "2025-05-15",
    endDate: "2025-05-18",
    address: "Sharjah, UAE",
    paymentStatus: "Pending",
    status: "Awaiting Payment",
    amount: "AED 1000",
    contractAmount: "₹10000",
    staffAccepted: true,
    userConfirmed: false,
    staffMessage: "Please complete payment to confirm the booking.",
    staffId: "3",
    staffName: "Michael Smith",
  },
  {
    id: 4,
    user: "Sneha",
    startDate: "2025-06-20",
    endDate: "2025-06-22",
    address: "Abu Dhabi, UAE",
    paymentStatus: "Paid",
    status: "Confirmed",
    amount: "AED 1200",
    contractAmount: "₹12000",
    staffAccepted: true,
    userConfirmed: true,
    staffMessage: "Booking successfully confirmed!",
    staffId: "4",
    staffName: "Sophia Fernandes",
  },
];

export default BookingData;
